######################################################################
# Automatically generated by qmake (3.1) Sun Apr 30 20:14:39 2017
######################################################################
QT += widgets
TEMPLATE = app
TARGET = snake
INCLUDEPATH += .

# Input
HEADERS += Snake.h
SOURCES += main.cpp Snake.cpp
